"""Dependency configuration for aggregation pipeline.

Startup Layer - Composition Root

Hexagonal Architecture - Composition Root Pattern:
Builds and wires together the application hexagon by:
1. Loading configuration from YAML files
2. Creating run directory
3. Instantiating driven adapters
4. Assembling the domain service with its dependencies

This is the composition root where all dependency wiring happens.
NOT unit tested - tested via CLI integration tests.
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional

from llm_ensemble.aggregate.domain.aggregation_service import AggregationService
from llm_ensemble.aggregate.registry import AggregationStrategyBuilder
from llm_ensemble.libs.config.io_config_loader import IOConfigFactory
from llm_ensemble.libs.runtime.path_manager import PathManager
from llm_ensemble.libs.runtime.tag_manager import TagManager
from llm_ensemble.libs.runtime.run_info import RunType
from llm_ensemble.libs.logging import configure_logger


def build_application(
    aggregation_strategy_name: str,
    io_name: str,
    run_name: str,
    official: bool = False,
    tag: Optional[str] = None,
) -> AggregationService:
    """Build and wire the aggregation application hexagon.

    Pure dependency wiring - no business logic.

    Composition root responsibilities:
    1. Load I/O configuration from YAML files
    2. Create run directory from provided run_name
    3. Instantiate adapter implementations
    4. Wire adapters into domain service

    The CLI generates the run_name from configuration metadata.

    Args:
        aggregation_strategy_name: Aggregation strategy name (e.g., 'majority_vote')
        io_name: I/O adapter name (e.g., 'json', 'db')
        run_name: Run identifier (generated by CLI from config metadata)
        official: Mark as official run (creates in official/ subdirectory)
        tag: Optional tag name for easy reference by downstream CLIs

    Returns:
        AggregationService with all dependencies wired
    """
    # Load I/O configuration from YAML
    io_config = IOConfigFactory.load(io_name, cli_name="aggregate")

    # Create run directory
    run_dir: Path = PathManager.get_run_dir("aggregate", run_name, official)
    run_dir.mkdir(parents=True, exist_ok=True)

    # Configure logging infrastructure (reads from environment)
    run_type = RunType.OFFICIAL if official else RunType.TEST
    configure_logger(
        cli_name="aggregate",
        run_name=run_name,
        run_type=run_type.value,
        log_file_path=run_dir / "run.log",
    )

    # Create tag symlink if requested
    if tag:
        TagManager.create_tag(run_dir, tag)

    # Build application hexagon with loaded configs
    return _build_application_hexagon(
        aggregation_strategy_name=aggregation_strategy_name,
        io_config=io_config,
        run_dir=run_dir,
    )


def _build_application_hexagon(
    aggregation_strategy_name: str,
    io_config,
    run_dir: Path,
) -> AggregationService:
    """Build application hexagon by instantiating driven adapters and service.

    This is the core of hexagonal architecture: assembling the application
    by plugging concrete adapters (driven side) into the domain service.

    Driven ports (infrastructure dependencies):
    - JudgementReader: Reading InferRunOutput records
    - AggregatedJudgementWriter: Writing AggregatedDataset records
    - AggregationStrategyPort: Strategy for aggregating votes

    Logging configuration is read from environment variables during application execution.

    Args:
        aggregation_strategy_name: Strategy name for factory
        io_config: Loaded I/O configuration
        run_dir: Run directory path (created by composition root)

    Returns:
        AggregationService - the domain service with all dependencies
    """
    # Instantiate adapters
    aggregation_strategy = AggregationStrategyBuilder.build(aggregation_strategy_name)
    reader = io_config.get_reader()
    writer = io_config.get_writer()

    # Assemble application hexagon (domain service with driven ports)
    return AggregationService(
        judgement_reader=reader,
        aggregated_judgement_writer=writer,
        aggregation_strategy_adapter=aggregation_strategy,
    )
