"""Dependency configuration for aggregation pipeline.

Startup Layer - Composition Root

Hexagonal Architecture - Composition Root Pattern:
Builds and wires together the application hexagon by:
1. Loading configuration from YAML files
2. Creating run directory
3. Instantiating driven adapters
4. Assembling the application with its dependencies

This is the composition root where all dependency wiring happens.
NOT unit tested - tested via CLI integration tests.
"""
from __future__ import annotations

from pathlib import Path

# Load runtime env configuration (DATABASE_URL, API keys, etc.)
from llm_ensemble.libs.runtime.env import load_runtime_config
load_runtime_config()

from llm_ensemble.aggregate.application.aggregation_application import AggregationApplication
from llm_ensemble.aggregate.application.ports.driving.for_running_aggregation import ForRunningAggregation
from llm_ensemble.aggregate.adapters.driven.aggregation_strategy_factory import AggregationStrategyBuilder
from llm_ensemble.aggregate.adapters.driven.io_factory import IOAdapterFactory
from llm_ensemble.libs.runtime.path_manager import PathManager
from llm_ensemble.libs.runtime.run_info import RunType
from llm_ensemble.libs.logging.structlog_logger import configure_logger


def build_application(
    aggregation_strategy_name: str,
    io_name: str,
    run_name: str,
    official: bool = False,
) -> ForRunningAggregation:
    """Build and wire the aggregation application hexagon.

    Pure dependency wiring - no business logic.

    Composition root responsibilities:
    1. Create run directory from provided run_name
    2. Instantiate adapter implementations
    3. Wire adapters into application

    The CLI generates the run_name from configuration metadata.

    Args:
        aggregation_strategy_name: Aggregation strategy name (e.g., 'majority_vote')
        io_name: I/O adapter name (e.g., 'db_to_db')
        run_name: Run identifier (generated by CLI from config metadata)
        official: Mark as official run (creates in official/ subdirectory)

    Returns:
        Application implementing ForRunningAggregation interface
    """
    # Create run directory
    run_dir: Path = PathManager.get_run_dir("aggregate", run_name, official)
    run_dir.mkdir(parents=True, exist_ok=True)

    # Configure logging infrastructure (reads from environment)
    run_type = RunType.OFFICIAL if official else RunType.TEST
    configure_logger(
        cli_name="aggregate",
        run_name=run_name,
        run_type=run_type.value,
        log_file_path=run_dir / "run.log",
    )

    # Build application hexagon
    return _build_application_hexagon(
        aggregation_strategy_name=aggregation_strategy_name,
        io_name=io_name,
        run_dir=run_dir,
        run_name=run_name,
    )


def _build_application_hexagon(
    aggregation_strategy_name: str,
    io_name: str,
    run_dir: Path,
    run_name: str,
) -> AggregationApplication:
    """Build application hexagon by instantiating driven adapters and application.

    This is the core of hexagonal architecture: assembling the application
    by plugging concrete adapters (driven side) into the use case.

    Driven ports (infrastructure dependencies):
    - ForInput: Reading InferRunOutput records
    - ForOutput: Writing AggregateRun records
    - ForAggregating: Strategy for aggregating votes

    Logging configuration is read from environment variables during application execution.

    Args:
        aggregation_strategy_name: Strategy name for factory
        io_name: I/O format name (e.g., 'db_to_db')
        run_dir: Run directory path (created by composition root)
        run_name: Run identifier (generated by CLI)

    Returns:
        AggregationApplication - the application's driving port interface
    """
    # Instantiate adapters using factories
    aggregation_strategy = AggregationStrategyBuilder.build(aggregation_strategy_name)
    reader = IOAdapterFactory.create_reader(io_name)
    writer = IOAdapterFactory.create_writer(io_name)

    # Assemble application hexagon (application with driven ports)
    return AggregationApplication(
        reader=reader,
        writer=writer,
        aggregation_strategy=aggregation_strategy,
        run_dir=run_dir,
        run_name=run_name,
    )
