"""Application for LLM inference pipeline.

Application Layer - Hexagonal Architecture

This module contains the complete inference backend orchestration.
It implements the driving port (ForRunningInference) and handles:
- Infrastructure setup (run directories, logging)
- Inference pipeline execution via driven ports
- Result persistence and finalization

This is the backend that both CLI and Web adapters use.
Depends only on port abstractions for testability.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional
from datetime import datetime

from llm_ensemble.infer.domain.entities.llm_judgement import LLMJudgement
from llm_ensemble.infer.domain.llm_judgement_builder import LLMJudgementBuilder
from llm_ensemble.infer.domain.entities.infer_run import InferRun
from llm_ensemble.infer.domain.metrics import (
    calculate_agreement,
    get_extracted_score,
    count_failed_parses,
    calculate_average_latency,
    aggregate_parse_issues,
    calculate_total_cost,
    calculate_total_prompt_tokens,
    calculate_total_completion_tokens,
    calculate_total_tokens,
)
from llm_ensemble.infer.domain.entities.parse_issues import issue_to_string
from llm_ensemble.infer.domain.entities.infer_run_summary import InferRunSummary
from llm_ensemble.infer.application.write_summary import WriteSummary
from llm_ensemble.infer.domain.infer_run_config_factory import InferRunConfigFactory
from llm_ensemble.infer.domain.dataset_utils import resolve_slice_indices

# Driving port (application implements this)
from llm_ensemble.infer.application.ports.driving.for_running_inference import ForRunningInference

# Driven ports (application depends on these)
from llm_ensemble.infer.application.ports.driven.for_invoking_llm import ForInvokingLLM
from llm_ensemble.infer.application.ports.driven.for_input import ForInput
from llm_ensemble.infer.application.ports.driven.for_output import ForOutput
from llm_ensemble.infer.application.ports.driven.for_parsing_responses import ForParsingResponses
from llm_ensemble.infer.application.ports.driven.for_building_prompts import ForBuildingPrompts

from llm_ensemble.libs.logging.structlog_logger import get_logger
from llm_ensemble.libs.logging.log_events import InferLogEvent
from llm_ensemble.libs.runtime.run_info import RunType
from llm_ensemble.libs.runtime.run_manager import persist_run_summary


class InferenceApplication(ForRunningInference):
    """Application use case for coordinating LLM inference pipeline.

    Implements the driving port ForRunningInference - this IS the application's API.
    Driving adapters (CLI, Web API, etc.) call the execute() method.

    This is the backend application that handles:
    - Logging configuration
    - Inference execution (read → prompt → infer → parse → write loop)
    - Result persistence and finalization

    Infrastructure setup (run directories, run naming) is handled by the
    composition root before application instantiation.

    Driving adapters are thin wrappers that:
    - Parse input (CLI args, HTTP requests)
    - Call this application
    - Present results (terminal output, HTTP responses)

    Depends only on driven port abstractions, enabling unit testing with mocked ports.
    """

    def __init__(
        self,
        input_port: ForInput,
        output_port: ForOutput,
        prompt_builder: ForBuildingPrompts,
        llm_provider: ForInvokingLLM,
        response_parser: ForParsingResponses,
        run_dir: Path,
        run_name: str,
    ):
        """Initialize inference use case with port dependencies.

        Args:
            input_port: Port for reading input data
            output_port: Port for writing output data
            prompt_builder: Port for building prompts from samples
            llm_provider: Port for LLM inference
            response_parser: Port for parsing LLM responses
            run_dir: Run directory path (created by composition root)
            run_name: Run identifier (generated by CLI)
        """
        self.input_port = input_port
        self.output_port = output_port
        self.prompt_builder = prompt_builder
        self.llm_provider = llm_provider
        self.response_parser = response_parser
        self.run_dir = run_dir
        self.run_name = run_name

    def run_inference(
        self,
        input_run_name: str,
        start_idx: Optional[int],
        end_idx: Optional[int],
        official: bool,
        notes: Optional[str],
    ) -> InferRunSummary:
        """Execute the complete inference backend with infrastructure setup and finalization.

        This is the main application entry point called by driving adapters (CLI, Web API).

        Backend workflow:
        - Setup logging
        - Read dataset samples via InputPort
        - For each sample: build prompt → infer → parse → write (streaming loop)
        - Write summary and finalize outputs
        - Return summary statistics

        Run directory and run name are provided at construction time by the
        composition root.

        All logging configured here appears in the driving adapter's output
        (terminal for CLI, CloudWatch for web API, etc.).

        Args:
            input_run_name: Ingest run identifier to read samples from
            start_idx: Start index into NormalizedDataset (None = from beginning)
            end_idx: End index into NormalizedDataset (None = until end)
            official: Mark as official run
            notes: Notes about this run (experiment purpose, hypothesis, etc.)

        Returns:
            InferRunSummary with statistics, timing, and warnings

        Raises:
            Exception: If any step in the pipeline fails
        """
        # Track start time for summary
        start_time = datetime.now()

        # Get logger
        logger = get_logger()
        logger.info(
            InferLogEvent.INFER_STARTED,
            name=self.run_name
        )

        # Read NormalizedDataset
        normalized_dataset = self.input_port.read(input_run_name)
        logger.info(InferLogEvent.INPUT_READ)

        # Slice to get samples that we want to judge
        actual_start_idx, actual_end_idx = resolve_slice_indices(normalized_dataset, start_idx, end_idx)
        samples_to_process = normalized_dataset.samples[actual_start_idx:actual_end_idx]

        # Collect judgements for summary statistics
        llm_judgements: list[LLMJudgement] = []

        # Build InferRun for early persistence
        infer_run = self._build_infer_run(
            run_name=self.run_name,
            official=official,
            notes=notes,
            input_run_name=input_run_name,
            start_idx=actual_start_idx,
            end_idx=actual_end_idx,
            start_time=start_time,
        )

        # Open writer for streaming
        with self.output_port.open(infer_run) as writer:

            # Process each dataset sample in slice
            for dataset_sample in samples_to_process:

                # Initialize builder for this sample
                builder = LLMJudgementBuilder(dataset_sample)

                # Step 1: Build prompt
                logger.info(InferLogEvent.BUILDING_PROMPT)
                prompt_text = self.prompt_builder.build_prompt(dataset_sample)
                builder.with_prompt(prompt_text)

                # Step 2: Run inference
                logger.info(InferLogEvent.SENDING_REQUEST)
                raw_response_text, invocation_metrics = self.llm_provider.infer(prompt_text)
                builder.with_llm_response(raw_response_text, invocation_metrics)
                logger.info(InferLogEvent.RESPONSE_RECEIVED, latency_s=round(invocation_metrics.latency_ms / 1000))
                logger.info(InferLogEvent.COST_CALCULATED,cost_estimate_usd=invocation_metrics.cost_estimate_usd)

                # Step 3: Parse response
                logger.info(InferLogEvent.PARSING_RESPONSE)
                llm_score, parse_issues = self.response_parser.parse(raw_response_text)
                builder.with_parsed_score(llm_score, parse_issues)
                if parse_issues:
                    for issue in parse_issues:
                        logger.warning(issue_to_string(issue))

                # Build complete judgement
                judgement = builder.build()

                logger.info(
                    InferLogEvent.JUDGEMENT_PROCESSED,
                    extracted_score=get_extracted_score(judgement),
                    gold_score=judgement.dataset_sample.judging_sample.gold_score.value,
                    agreement=calculate_agreement(judgement),
                )

                # Write judgement immediately to disk (fault tolerance!)
                writer.write_one(judgement)

                logger.debug(
                    InferLogEvent.JUDGEMENT_COMPLETE,
                    prompt=judgement.llm_prompt_text.prompt_text,
                    llm_response=judgement.llm_response_text.llm_response_text,
                    llm_score=judgement.llm_score.model_dump() if judgement.llm_score else None,
                )
                # Collect for summary statistics
                llm_judgements.append(judgement)


        # Retrieve persistence summary after context manager closes
        write_summary = self.output_port.get_write_summary()

        # Build run summary
        run_summary = self._build_run_summary(start_time, llm_judgements, write_summary)

        # Write run summary to disk and log completion
        run_summary_path = persist_run_summary(run_summary, self.run_dir)
        logger.info(InferLogEvent.INFER_RUN_SUMMARY_WRITTEN, path=str(run_summary_path))

        # Return finalized run summary
        return run_summary

    def _build_infer_run(
        self,
        run_name: str,
        official: bool,
        notes: Optional[str],
        input_run_name: str,
        start_idx: int,
        end_idx: int,
        start_time: datetime,
    ) -> InferRun:
        """Build InferRun aggregate root for early persistence.

        Created with config present but output=None (set at close).

        Application layer responsibility: extract domain entities from ports,
        then assemble into aggregate root.

        Args:
            run_name: Run name
            official: Whether this is an official run
            notes: Optional notes about this run
            input_run_name: Resolved ingest run name
            start_idx: Actual start index used
            end_idx: Actual end index used
            start_time: When the run started

        Returns:
            InferRun aggregate root (config present, output=None, start_time present, end_time=None)
        """
        # Extract domain entities from adapters
        provider = self.llm_provider.get_provider()
        model_config = self.llm_provider.get_model_config()
        retry_config = self.llm_provider.get_retry_config()
        prompt_builder_entity = self.prompt_builder.get_builder()
        response_parser_entity = self.response_parser.get_parser()
        template_text = self.prompt_builder.get_template_text()
        io_name = self.output_port.io_name

        # Build config via factory
        run_config = InferRunConfigFactory.create(
            provider=provider,
            model_config=model_config,
            retry_config=retry_config,
            prompt_builder=prompt_builder_entity,
            response_parser=response_parser_entity,
            template_text=template_text,
            io_name=io_name,
            input_run_name=input_run_name,
            start_idx=start_idx,
            end_idx=end_idx,
        )

        # Build InferRun aggregate root (output=None at this stage)
        return InferRun(
            run_name=run_name,
            run_type=RunType.OFFICIAL if official else RunType.TEST,
            notes=notes,
            infer_run_config=run_config,
            infer_run_output=None,  # Set at close time
            start_time=start_time,
            end_time=None,  # Set at close time
        )

    def _build_run_summary(
        self,
        start_time: datetime,
        llm_judgements: list[LLMJudgement],
        write_summary: WriteSummary,
    ) -> InferRunSummary:
        """Build run summary from execution results.

        Args:
            start_time: Time when inference pipeline started
            llm_judgements: List of all judgements produced
            write_summary: Write operation summary from output port

        Returns:
            Complete InferRunSummary with all statistics
        """
        # Calculate domain statistics using focused functions
        failed_parses_count = count_failed_parses(llm_judgements)
        total_latency_ms = sum(j.llm_invocation_metrics.latency_ms for j in llm_judgements)
        avg_latency_ms = calculate_average_latency(llm_judgements)
        issues_summary = aggregate_parse_issues(llm_judgements)
        total_cost_usd = calculate_total_cost(llm_judgements)
        total_prompt_tokens = calculate_total_prompt_tokens(llm_judgements)
        total_completion_tokens = calculate_total_completion_tokens(llm_judgements)
        total_tokens = calculate_total_tokens(llm_judgements)

        # Construct Pydantic summary
        return InferRunSummary(
            start_time=start_time,
            end_time=datetime.now(),
            write_summary=write_summary,
            judgement_count=len(llm_judgements),
            failed_parses_count=failed_parses_count,
            total_latency_ms=total_latency_ms,
            avg_latency_ms=avg_latency_ms,
            total_cost_usd=total_cost_usd,
            total_prompt_tokens=total_prompt_tokens,
            total_completion_tokens=total_completion_tokens,
            total_tokens=total_tokens,
            issues_summary=issues_summary,
        )
