"""Application for data ingestion pipeline.

Application Layer - Hexagonal Architecture

This module contains the complete ingestion backend orchestration.
It implements the driving port (ForRunningIngest) and handles:
- Infrastructure setup (run directories, logging)
- Dataset normalization via driven ports
- Result persistence and finalization

This is the backend that both CLI and Web adapters use.
Depends only on port abstractions for testability.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from llm_ensemble.ingest.domain.entities.normalized_dataset import NormalizedDataset
from llm_ensemble.ingest.domain.entities.ingest_run_info import IngestRunInfo
from llm_ensemble.ingest.domain.entities.ingest_run_config import IngestRunConfig
from llm_ensemble.ingest.domain.entities.ingest_run_summary import IngestRunSummary

# Driving port (application implements this)
from llm_ensemble.ingest.application.ports.driving.for_running_ingest import ForRunningIngest

# Driven ports (application depends on these)
from llm_ensemble.ingest.application.ports.driven.for_input import ForInput
from llm_ensemble.ingest.application.ports.driven.for_output import ForOutput

from llm_ensemble.libs.logging import get_logger
from llm_ensemble.libs.logging.log_events import IngestLogEvent
from llm_ensemble.libs.runtime.run_info import RunType
from llm_ensemble.libs.runtime.run_manager import write_summary
from llm_ensemble.libs.runtime.run_summary_builder import RunSummaryBuilder

# Load runtime env configuration
from llm_ensemble.libs.runtime.env import load_runtime_config
load_runtime_config()


class IngestApplication(ForRunningIngest):
    """Application use case for coordinating data ingestion pipeline.

    Implements the driving port ForRunningIngest - this IS the application's API.
    Driving adapters (CLI, Web API, etc.) call the run_ingest() method.

    This is the backend application that handles:
    - Logging configuration
    - Dataset normalization (read → write)
    - Result persistence and finalization

    Infrastructure setup (run directories, run naming) is handled by the
    composition root before application instantiation.

    Driving adapters are thin wrappers that:
    - Parse input (CLI args, HTTP requests)
    - Call this application
    - Present results (terminal output, HTTP responses)

    Depends only on driven port abstractions, enabling unit testing with mocked ports.
    """

    def __init__(
        self,
        dataset_reader: ForInput,
        dataset_writer: ForOutput,
        run_dir: Path,
        run_name: str,
        io_config_name: str,
    ):
        """Initialize ingest use case with port dependencies.

        Args:
            dataset_reader: Port for reading and normalizing datasets
            dataset_writer: Port for writing judging samples
            run_dir: Run directory path (created by composition root)
            run_name: Run identifier (generated by CLI or provided by user)
            io_config_name: Name of the I/O config file for metadata
        """
        self.dataset_reader = dataset_reader
        self.dataset_writer = dataset_writer
        self.run_dir = run_dir
        self.run_name = run_name
        self.io_config_name = io_config_name

    def run_ingest(
        self,
        input_path: Path,
        limit: Optional[int],
        official: bool,
        notes: Optional[str],
    ) -> IngestRunSummary:
        """Execute the complete ingestion backend with infrastructure setup and finalization.

        This is the main application entry point called by driving adapters.

        Backend workflow:
        - Setup logging
        - Verify input path exists
        - Build run_info for manifest
        - Read and normalize dataset via DatasetReader port
        - Write normalized samples via DatasetWriter port
        - Write summary and finalize outputs
        - Return summary statistics

        Run directory and run name are provided at construction time by the
        composition root.

        All logging configured here appears in the driving adapter's output
        (terminal for CLI, CloudWatch for web API, etc.).

        Args:
            input_path: Path to input directory containing raw dataset files
            limit: Process at most N samples
            official: Mark as official run
            notes: Notes about this run (experiment purpose, hypothesis, etc.)

        Returns:
            IngestRunSummary with statistics and timing

        Raises:
            FileNotFoundError: If input path doesn't exist
            ValueError: If adapter is not recognized or dataset files are malformed
            Exception: If any step in the pipeline fails
        """
        # Get logger
        logger = get_logger()
        logger.info(IngestLogEvent.INGEST_STARTED)

        # Create run summary builder (for timing and collection of metrics)
        summary_builder = RunSummaryBuilder()
        summary_builder.set_start_time()

        # Read and normalize dataset
        normalized_dataset: NormalizedDataset = self.dataset_reader.read(
            input_path,
            limit=limit
        )
        logger.info(
            IngestLogEvent.DATASET_READ_COMPLETE,
            sample_count=normalized_dataset.sample_count,
        )

        # Write output
        run_config = self._build_run_config(
            io_config_name=self.io_config_name,
            input_path=input_path,
            limit=limit,
        )
        run_info = self._build_run_info(
            run_name=self.run_name,
            official=official,
            notes=notes,
        )
        write_summary = self.dataset_writer.write(
            normalized_dataset,
            run_info,
            run_config
        )

        # Add to write summary to builder for inclusion in final summary
        summary_builder.add("write_summary", write_summary)
        summary_builder.add("sample_count", normalized_dataset.sample_count)

        # Finalize summary (sets end_time and creates immutable Pydantic object)
        summary: IngestRunSummary = summary_builder.finalize(IngestRunSummary)

        # Write summary.json
        summary_path = write_summary(summary, self.run_dir)
        logger.info(IngestLogEvent.INGEST_SUMMARY_WRITTEN, path=str(summary_path))
        
        # Return finalized summary
        return summary


    def _build_run_config(
        self,
        io_config_name: str,
        input_path: Path,
        limit: Optional[int],
    ) -> IngestRunConfig:
        """Build run config for manifest.

        Args:
            io_config_name: Name of the I/O config file
            input_path: Path to input directory
            limit: Optional limit on samples to process

        Returns:
            IngestRunConfig for manifest persistence
        """
        return IngestRunConfig(
            io_config_name=io_config_name,
            input_path=str(input_path),
            limit=limit,
        )

    def _build_run_info(
        self,
        run_name: str,
        official: bool,
        notes: Optional[str],
    ) -> IngestRunInfo:
        """Build IngestRunInfo entity for manifest persistence.

        Args:
            run_name: Run identifier
            official: Whether this is an official run
            notes: Optional notes about this run

        Returns:
            IngestRunInfo entity
        """
        return IngestRunInfo(
            run_name=run_name,
            run_type=RunType.OFFICIAL if official else RunType.TEST,
            notes=notes,
        )
