name: thomas-et-al-prompt
description: |
  Thomas et al. search quality rater prompt with structured JSON output.
  Uses simple O-only format for relevance scoring (0, 1, or 2).
prompt_template: thomas-et-al-prompt
prompt_builder: thomas
response_parser: thomas
