"""Dependency configuration for evaluation pipeline.

Startup Layer - Composition Root

Hexagonal Architecture - Composition Root Pattern:
Builds and wires together the application hexagon by:
1. Loading configuration from YAML files (future)
2. Creating run directory (infrastructure concern)
3. Instantiating driven adapters (ports implementations)
4. Assembling the use case with its dependencies
5. Returning the application's driving port interface

This is the composition root where all dependency wiring happens.
NOT unit tested - tested via CLI integration tests.

The driving adapter (CLI) calls this configurator to build the application,
then uses the returned ForRunningEvaluation interface to execute business logic.
"""

from __future__ import annotations
from pathlib import Path

# Load runtime env configuration (DATABASE_URL, API keys, etc.)
from llm_ensemble.libs.runtime.env import load_runtime_config
load_runtime_config()

from llm_ensemble.evaluate.application.evaluation_application import EvaluationApplication
from llm_ensemble.evaluate.application.ports.driving.for_running_evaluation import ForRunningEvaluation

from llm_ensemble.evaluate.adapters.driven.io_factory import IOAdapterFactory
from llm_ensemble.evaluate.adapters.driven.metric_factory import MetricAdapterFactory

from llm_ensemble.libs.runtime.path_manager import PathManager
from llm_ensemble.libs.runtime.run_info import RunType
from llm_ensemble.libs.logging.structlog_logger import configure_logger


def build_application(
    io_name: str,
    run_name: str,
    official: bool = False,
) -> ForRunningEvaluation:
    """Build and wire the evaluation application hexagon.

    Pure dependency wiring - no business logic.

    Composition root responsibilities:
    1. Load configuration from YAML files (future)
    2. Create run directory from provided run_name
    3. Instantiate adapter implementations
    4. Wire adapters into application

    The CLI generates the run_name from configuration metadata.

    Args:
        io_name: I/O adapter name (e.g., 'dummy')
        run_name: Run identifier (generated by CLI from config metadata)
        official: Mark as official run (creates in official/ subdirectory)

    Returns:
        Application implementing ForRunningEvaluation interface
    """
    # Create run directory
    run_dir: Path = PathManager.get_run_dir("evaluate", run_name, official)
    run_dir.mkdir(parents=True, exist_ok=True)

    # Configure logging infrastructure
    run_type = RunType.OFFICIAL if official else RunType.TEST
    configure_logger(
        cli_name="evaluate",
        run_name=run_name,
        run_type=run_type.value,
        log_file_path=run_dir / "run.log",
    )

    # Build application hexagon with loaded configs
    return _build_application_hexagon(
        io_name=io_name,
        run_dir=run_dir,
        run_name=run_name,
    )


def _build_application_hexagon(
    io_name: str,
    run_dir: Path,
    run_name: str,
) -> EvaluationApplication:
    """Build application hexagon by instantiating driven adapters and use case.

    This is the core of hexagonal architecture: assembling the application
    by plugging concrete adapters (driven side) into the use case.

    Driven ports (infrastructure dependencies):
    - InputPort: Reading evaluation data from runs
    - OutputPort: Writing evaluation reports
    - MetricPorts: Computing evaluation metrics

    The use case depends only on port abstractions (ABCs), enabling:
    - Unit testing with mocked ports
    - Swapping implementations via configuration

    Args:
        io_name: I/O adapter name for factory
        run_dir: Run directory path (created by composition root)
        run_name: Run identifier (generated by CLI)

    Returns:
        EvaluationApplication - the application's driving port interface
    """
    input_port = IOAdapterFactory.create_reader(io_name)
    output_port = IOAdapterFactory.create_writer(io_name, run_dir=run_dir)

    # For now, hardcode metrics list
    # Future: load metric list from config
    metric_adapters = [
        MetricAdapterFactory.create("cohens_kappa"),
        MetricAdapterFactory.create("krippendorffs_alpha"),
    ]

    # Assemble application hexagon (use case with driven ports)
    return EvaluationApplication(
        input_port=input_port,
        output_port=output_port,
        metric_adapters=metric_adapters,
        run_name=run_name,
    )
