"""Dependency configuration for ingestion pipeline.

Startup Layer - Composition Root

Hexagonal Architecture - Composition Root Pattern:
Builds and wires together the application hexagon by:
1. Loading configuration from YAML files
2. Creating run directory (infrastructure concern)
3. Instantiating driven adapters (ports implementations)
4. Assembling the use case with its dependencies
5. Returning the application's driving port interface

This is the composition root where all dependency wiring happens.
NOT unit tested - tested via CLI integration tests.

The driving adapter (CLI) calls this configurator to build the application,
then uses the returned ForRunningIngest interface to execute business logic.
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional

from llm_ensemble.ingest.application.ingest_application import IngestApplication
from llm_ensemble.ingest.application.ports.driving.for_running_ingest import ForRunningIngest
from llm_ensemble.libs.schemas import IOConfig

from llm_ensemble.libs.runtime.path_manager import PathManager
from llm_ensemble.libs.runtime.tag_manager import TagManager
from llm_ensemble.libs.runtime.run_info import RunType
from llm_ensemble.libs.logging import configure_logger


def build_application(
    io_config: IOConfig,
    io_config_name: str,
    run_name: str,
    official: bool = False,
    tag: Optional[str] = None,
) -> ForRunningIngest:
    """Build and wire the ingestion application hexagon.

    Pure dependency wiring - no business logic.

    Composition root responsibilities:
    1. Load configuration from YAML files (already done by CLI)
    2. Create run directory from provided run_name
    3. Instantiate adapter implementations from config
    4. Wire adapters into application

    The CLI generates the run_name from configuration metadata and loads
    the io_config with any overrides applied.

    Args:
        io_config: Ingest-specific I/O configuration (already loaded and validated)
        io_config_name: Name of the I/O config file (e.g., "llm_judge_ingest")
        run_name: Run identifier (generated by CLI from config metadata)
        official: Mark as official run (creates in official/ subdirectory)
        tag: Optional tag name for easy reference by downstream CLIs

    Returns:
        Application implementing ForRunningIngest interface
    """
    # Create run directory
    run_dir: Path = PathManager.get_run_dir("ingest", run_name, official)
    run_dir.mkdir(parents=True, exist_ok=True)

    # Configure logging infrastructure
    run_type = RunType.OFFICIAL if official else RunType.TEST
    configure_logger(
        cli_name="ingest",
        run_name=run_name,
        run_type=run_type.value,
        log_file_path=run_dir / "run.log",
    )

    # Create tag symlink if requested
    if tag:
        TagManager.create_tag(run_dir, tag)

    # Build application hexagon with loaded config
    return _build_application_hexagon(
        io_config=io_config,
        io_config_name=io_config_name,
        run_dir=run_dir,
        run_name=run_name,
    )


def _build_application_hexagon(
    io_config: IOConfig,
    io_config_name: str,
    run_dir: Path,
    run_name: str,
) -> IngestApplication:
    """Build application hexagon by instantiating driven adapters and use case.

    This is the core of hexagonal architecture: assembling the application
    by plugging concrete adapters (driven side) into the use case.

    Driven ports (infrastructure dependencies):
    - DatasetReader: Reading and normalizing raw datasets
    - DatasetWriter: Writing normalized samples

    The use case depends only on port abstractions (ABCs), enabling:
    - Unit testing with mocked ports
    - Swapping implementations via configuration

    Logging configuration is read from environment variables during application execution.

    Args:
        io_config: Loaded I/O configuration
        io_config_name: Name of the I/O config file for metadata
        run_dir: Run directory path (created by composition root)
        run_name: Run identifier (generated by CLI)

    Returns:
        IngestApplication - the application's driving port interface
    """
    # Instantiate adapters directly from config
    dataset_reader = io_config.get_reader()
    dataset_writer = io_config.get_writer()

    # Assemble application hexagon (use case with driven ports)
    return IngestApplication(
        dataset_reader=dataset_reader,
        dataset_writer=dataset_writer,
        run_dir=run_dir,
        run_name=run_name,
        io_config_name=io_config_name,
    )
