name_hint: majority-vote
aggregation_strategy_name: majority_vote
aggregation_strategy_adapter:
  aggregation_strategy_module: llm_ensemble.aggregate.adapters.strategies.majority_vote_adapter
  aggregation_strategy_class: MajorityVoteAdapter
