"""Application for aggregation pipeline.

Application Layer - Hexagonal Architecture

This module contains the complete aggregation backend orchestration.
It handles:
- Infrastructure setup (run directories, logging)
- Aggregation pipeline execution via driven ports
- Result persistence and finalization

This is the backend that the CLI adapter uses.
Depends only on port abstractions for testability.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional
from uuid import UUID
from collections import defaultdict
from datetime import datetime

from llm_ensemble.infer.domain.entities.infer_run_output import InferRunOutput
from llm_ensemble.infer.domain.entities.llm_judgement import LLMJudgement
from llm_ensemble.aggregate.domain.entities.aggregated_dataset import AggregatedDataset
from llm_ensemble.aggregate.domain.entities.aggregated_vote import AggregatedVote
from llm_ensemble.aggregate.domain.entities.aggregate_run_summary import AggregateRunSummary
from llm_ensemble.aggregate.domain.aggregate_run_factory import AggregateRunFactory
from llm_ensemble.aggregate.application.ports.aggregated_judgement_writer import AggregatedJudgementWriter
from llm_ensemble.aggregate.application.ports.aggregation_strategy import AggregationStrategyPort
from llm_ensemble.aggregate.application.ports.judgement_reader import JudgementReader

from llm_ensemble.libs.logging import get_logger
from llm_ensemble.libs.logging.log_events import AggregateLogEvent
from llm_ensemble.libs.runtime.run_info import RunType
from llm_ensemble.libs.runtime.run_manager import write_summary
from llm_ensemble.libs.runtime.tag_manager import TagManager


class AggregationApplication:
    """Application use case for coordinating ensemble aggregation pipeline.

    This is the backend application that handles:
    - Logging configuration
    - Aggregation execution (read → group → aggregate → write loop)
    - Result persistence and finalization

    Infrastructure setup (run directories, run naming) is handled by the
    composition root before application instantiation.

    The CLI adapter is a thin wrapper that:
    - Parses CLI arguments
    - Calls this application
    - Presents results (terminal output)

    Depends only on driven port abstractions, enabling unit testing with mocked ports.
    """

    def __init__(
        self,
        reader: JudgementReader,
        writer: AggregatedJudgementWriter,
        aggregation_strategy: AggregationStrategyPort,
        run_dir: Path,
        run_name: str,
        io_name: str,
        aggregation_strategy_name: str,
    ):
        """Initialize aggregation use case with port dependencies.

        Args:
            reader: Port for reading InferRunOutput records
            writer: Port for writing AggregateRun
            aggregation_strategy: Port for aggregation strategy (e.g., MajorityVoteAdapter)
            run_dir: Run directory path (created by composition root)
            run_name: Run identifier (generated by CLI)
            io_name: Name of the I/O configuration used
            aggregation_strategy_name: Name of the aggregation strategy used
        """
        self.input_port = reader
        self.output_port = writer
        self.strategy = aggregation_strategy
        self.run_dir = run_dir
        self.run_name = run_name
        self.io_name = io_name
        self.aggregation_strategy_name = aggregation_strategy_name

    def run_aggregation(
        self,
        input_run_names: list[str],
        official: bool,
        notes: Optional[str] = None,
    ) -> AggregateRunSummary:
        """Execute the complete aggregation backend with infrastructure setup and finalization.

        This is the main application entry point called by the CLI adapter.

        Backend workflow:
        - Setup logging and run metadata
        - Read InferRunOutputs via JudgementReader port
        - Validate sample_fingerprints match
        - Group judgements by dataset_sample_id
        - Apply aggregation strategy to each group
        - Create AggregatedDataset
        - Build AggregateRun entity
        - Write AggregateRun via writer port (batch persistence)
        - Write summary and finalize outputs
        - Return summary statistics

        Run directory and run name are provided at construction time by the
        composition root.

        Args:
            input_run_names: List of infer run identifiers to read judgements from
            official: Mark as official run
            notes: Notes about this run

        Returns:
            AggregateRunSummary with statistics, timing, and warnings

        Raises:
            ValueError: If validation fails or strategy not found
            FileNotFoundError: If any run directory doesn't exist
        """
        # Get logger
        logger = get_logger()
        logger.info(AggregateLogEvent.AGGREGATE_STARTED, name=self.run_name)

        # Track start time for summary
        start_time = datetime.now()

        # Read InferRunOutputs (one per run) via reader port
        resolved_run_names = [TagManager.resolve_input(rn, "infer") for rn in input_run_names]
        judged_datasets: list[InferRunOutput] = self.input_port.read(resolved_run_names)

        # Validate completion and sample_fingerprint consistency
        self._validate_judged_datasets(judged_datasets, resolved_run_names)

        # Log validation
        sample_fingerprints = {dataset.sample_fingerprint for dataset in judged_datasets}
        logger.info(
            AggregateLogEvent.DATASETS_VALIDATED,
            num_datasets=len(judged_datasets),
            shared_sample_fingerprint=list(sample_fingerprints)[0][:16] + "..." if sample_fingerprints else "N/A"
        )

        # Group llm_judgements by dataset_sample_id across all runs
        logger.info(AggregateLogEvent.GROUPING_JUDGEMENTS)
        grouped_by_sample: dict[UUID, list[LLMJudgement]] = defaultdict(list)

        for judged_dataset in judged_datasets:
            for llm_judgement in judged_dataset.llm_judgements:
                # Get dataset_sample_id via llm_prompt → dataset_sample
                dataset_sample_id = llm_judgement.llm_prompt.dataset_sample.id
                grouped_by_sample[dataset_sample_id].append(llm_judgement)

        # Track statistics
        tie_count = 0
        no_valid_votes_count = 0
        aggregated_votes = []

        # Process each dataset_sample_id
        logger.info(AggregateLogEvent.APPLYING_STRATEGY, strategy=self.aggregation_strategy_name)
        for dataset_sample_id in sorted(grouped_by_sample.keys()):
            # All llm_judgements for this sample (one from each run/model config)
            llm_judgements_for_sample = grouped_by_sample[dataset_sample_id]

            # Apply aggregation strategy to get AggregatedVote
            aggregated_vote: AggregatedVote = self.strategy.aggregate(llm_judgements_for_sample)

            # Track statistics
            if aggregated_vote.final_label is None:
                no_valid_votes_count += 1
            elif aggregated_vote.final_reasoning and "tie" in aggregated_vote.final_reasoning.lower():
                tie_count += 1

            aggregated_votes.append(aggregated_vote)

            # Log progress
            logger.info(
                AggregateLogEvent.SAMPLE_AGGREGATED,
                dataset_sample_id=str(dataset_sample_id)[:8] + "...",
                final_label=aggregated_vote.final_label.label if aggregated_vote.final_label else "None",
                confidence=f"{aggregated_vote.final_confidence:.2f}" if aggregated_vote.final_confidence else "0.00",
                num_llm_judgements=len(llm_judgements_for_sample),
            )

        # Create AggregatedDataset (computes fingerprint and UUID from votes)
        aggregated_dataset = AggregatedDataset.create(aggregated_votes)
        logger.info(
            AggregateLogEvent.DATASET_CREATED,
            dataset_id=str(aggregated_dataset.id)[:8] + "...",
            vote_count=aggregated_dataset.vote_count,
        )

        # Track end time
        end_time = datetime.now()

        # Build AggregateRun entity
        aggregate_run = AggregateRunFactory.create(
            aggregation_strategy_name=self.aggregation_strategy_name,
            io_config_name=self.io_name,
            input_run_names=resolved_run_names,
            run_name=self.run_name,
            run_type=RunType.OFFICIAL if official else RunType.TEST,
            aggregated_dataset=aggregated_dataset,
            start_time=start_time,
            end_time=end_time,
            notes=notes,
        )

        # Write output (batch persistence like ingest)
        write_result = self.output_port.write(aggregate_run)
        logger.info(AggregateLogEvent.AGGREGATE_COMPLETE)

        # Build summary
        total_llm_judgements = sum(
            len(judged_dataset.llm_judgements)
            for judged_dataset in judged_datasets
        )

        # Build warnings summary
        warnings_summary = {}
        if tie_count > 0:
            warnings_summary["tie"] = tie_count
        if no_valid_votes_count > 0:
            warnings_summary["no_valid_votes"] = no_valid_votes_count

        # Construct summary
        summary = AggregateRunSummary(
            start_time=start_time,
            end_time=end_time,
            input_judgement_count=total_llm_judgements,
            unique_pair_count=len(grouped_by_sample),
            output_aggregated_count=len(aggregated_votes),
            tie_count=tie_count,
            no_valid_votes_count=no_valid_votes_count,
            warnings_summary=warnings_summary if warnings_summary else None,
            write_summary=write_result,
        )

        # Write summary.json
        summary_path = write_summary(summary, self.run_dir)
        logger.info(AggregateLogEvent.AGGREGATE_SUMMARY_WRITTEN, path=str(summary_path))

        # Log warnings summary if any
        if summary.warnings_summary:
            logger.info(
                AggregateLogEvent.WARNINGS_COLLECTED,
                **summary.warnings_summary
            )

        return summary

    def _validate_judged_datasets(
        self, judged_datasets: list[InferRunOutput], run_names: list[str]
    ) -> None:
        """Validate that all InferRunOutputs are complete and compatible for aggregation.

        Checks:
        1. All InferRunOutputs have non-NULL sample_fingerprints (run completed successfully)
        2. All sample_fingerprints match (same samples were processed)

        Args:
            judged_datasets: List of InferRunOutput objects loaded by reader
            run_names: Corresponding run names (for error messages)

        Raises:
            ValueError: If validation fails
        """
        if not judged_datasets:
            raise ValueError("No InferRunOutputs found. Cannot aggregate empty list.")

        # Check for NULL sample_fingerprints (incomplete runs)
        for dataset, run_name in zip(judged_datasets, run_names):
            if dataset.sample_fingerprint is None:
                raise ValueError(
                    f"InferRunOutput for run '{run_name}' has NULL sample_fingerprint. "
                    f"This indicates the run did not complete successfully."
                )

        # Check that all sample_fingerprints match
        sample_fingerprints = {dataset.sample_fingerprint for dataset in judged_datasets}
        if len(sample_fingerprints) > 1:
            raise ValueError(
                f"Cannot aggregate runs with different InferRunOutput sample_fingerprints. "
                f"Found {len(sample_fingerprints)} distinct sample_fingerprints. "
                f"This means the runs processed different sets of samples."
            )
