"""Application for aggregation pipeline.

Application Layer - Hexagonal Architecture

This module contains the complete aggregation backend orchestration.
It implements the driving port (ForRunningAggregation) and handles:
- Infrastructure setup (run directories, logging)
- Aggregation pipeline execution via driven ports
- Result persistence and finalization

This is the backend that both CLI and Web adapters use.
Depends only on port abstractions for testability.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional
from uuid import UUID
from collections import defaultdict
from datetime import datetime

from llm_ensemble.infer.domain.entities.infer_run_output import InferRunOutput
from llm_ensemble.infer.domain.entities.llm_judgement import LLMJudgement
from llm_ensemble.aggregate.domain.entities.aggregated_vote import AggregatedVote
from llm_ensemble.aggregate.domain.entities.aggregate_run_summary import AggregateRunSummary
from llm_ensemble.aggregate.domain.aggregate_run_factory import AggregateRunFactory
from llm_ensemble.aggregate.domain.validation import validate_infer_run_outputs_for_aggregation
from llm_ensemble.aggregate.domain.aggregate_statistics import (
    calculate_total_judgements,
    build_warnings_summary,
)

# Driving port (application implements this)
from llm_ensemble.aggregate.application.ports.driving.for_running_aggregation import ForRunningAggregation

# Driven ports (application depends on these)
from llm_ensemble.aggregate.application.ports.driven.for_output import ForOutput
from llm_ensemble.aggregate.application.ports.driven.for_aggregating import ForAggregating
from llm_ensemble.aggregate.application.ports.driven.for_input import ForInput

from llm_ensemble.libs.logging import get_logger
from llm_ensemble.libs.logging.log_events import AggregateLogEvent
from llm_ensemble.libs.runtime.run_info import RunType
from llm_ensemble.libs.runtime.run_manager import write_summary


def _format_vote_breakdown(llm_judgements: list[LLMJudgement], final_label: Optional[int]) -> str:
    """Format vote breakdown string for logging.

    Shows individual votes and final result.
    Example: "0 0 1 → 0" (votes were 0, 0, 1, final is 0)
    """
    input_labels = [
        j.llm_score.label if j.llm_score and j.llm_score.label is not None else None
        for j in llm_judgements
    ]
    votes_str = " ".join(str(label) for label in input_labels)
    return f"{votes_str} → {final_label}"


class AggregationApplication(ForRunningAggregation):
    """Application use case for coordinating ensemble aggregation pipeline.

    Implements the driving port ForRunningAggregation - this IS the application's API.
    Driving adapters (CLI, Web API, etc.) call the run_aggregation() method.

    This is the backend application that handles:
    - Logging configuration
    - Aggregation execution (read → group → aggregate → write loop)
    - Result persistence and finalization

    Infrastructure setup (run directories, run naming) is handled by the
    composition root before application instantiation.

    Driving adapters are thin wrappers that:
    - Parse input (CLI args, HTTP requests)
    - Call this application
    - Present results (terminal output, HTTP responses)

    Depends only on driven port abstractions, enabling unit testing with mocked ports.
    """

    def __init__(
        self,
        reader: ForInput,
        writer: ForOutput,
        aggregation_strategy: ForAggregating,
        run_dir: Path,
        run_name: str,
    ):
        """Initialize aggregation use case with port dependencies.

        Args:
            reader: Port for reading InferRunOutput records
            writer: Port for writing AggregateRun
            aggregation_strategy: Port for aggregation strategy (e.g., MajorityVoteAdapter)
            run_dir: Run directory path (created by composition root)
            run_name: Run identifier (generated by CLI)
        """
        self.input_port = reader
        self.output_port = writer
        self.strategy = aggregation_strategy
        self.run_dir = run_dir
        self.run_name = run_name

    def run_aggregation(
        self,
        input_run_names: list[str],
        official: bool,
        notes: Optional[str] = None,
    ) -> AggregateRunSummary:
        """Execute the complete aggregation backend with infrastructure setup and finalization.

        This is the main application entry point called by the CLI adapter.

        Backend workflow:
        - Setup logging and run metadata
        - Read InferRunOutputs via JudgementReader port
        - Validate sample_fingerprints match
        - Group judgements by dataset_sample_id
        - Apply aggregation strategy to each group
        - Build AggregateRun entity via factory (creates AggregatedDataset)
        - Write AggregateRun via writer port (batch persistence)
        - Write summary and finalize outputs
        - Return summary statistics

        Run directory and run name are provided at construction time by the
        composition root.

        Args:
            input_run_names: List of infer run identifiers to read judgements from
            official: Mark as official run
            notes: Notes about this run

        Returns:
            AggregateRunSummary with statistics, timing, and warnings

        Raises:
            ValueError: If validation fails or strategy not found
            FileNotFoundError: If any run directory doesn't exist
        """
        # Get logger
        logger = get_logger()
        logger.info(AggregateLogEvent.AGGREGATE_STARTED, name=self.run_name)

        start_time = datetime.now()

        # Read InferRunOutputs (one per run) via reader port
        judged_datasets: list[InferRunOutput] = self.input_port.read(input_run_names)

        # Validate completion and sample_fingerprint consistency
        validate_infer_run_outputs_for_aggregation(judged_datasets, input_run_names)
        logger.info(
            AggregateLogEvent.DATASETS_VALIDATED,
            num_datasets=len(judged_datasets),
        )

        # Group llm_judgements by dataset_sample_id across all runs
        grouped_by_sample: dict[UUID, list[LLMJudgement]] = defaultdict(list)
        for judged_dataset in judged_datasets:
            for llm_judgement in judged_dataset.llm_judgements:
                dataset_sample_id = llm_judgement.dataset_sample.id
                grouped_by_sample[dataset_sample_id].append(llm_judgement)

        # Track statistics
        tie_count = 0
        no_valid_votes_count = 0
        aggregated_votes : list[AggregatedVote] = []

        for dataset_sample_id in sorted(grouped_by_sample.keys()):
            # All llm_judgements for this sample (one from each run/model config)
            llm_judgements_for_sample = grouped_by_sample[dataset_sample_id]

            # Apply aggregation strategy to get AggregatedVote
            aggregated_vote = self.strategy.aggregate(llm_judgements_for_sample)

            # Track statistics
            if aggregated_vote.final_label is None:
                no_valid_votes_count += 1
            elif aggregated_vote.final_reasoning and "tie" in aggregated_vote.final_reasoning.lower():
                tie_count += 1

            aggregated_votes.append(aggregated_vote)

            # Log progress with vote breakdown
            vote_breakdown = _format_vote_breakdown(llm_judgements_for_sample, aggregated_vote.final_label)
            logger.info(
                AggregateLogEvent.SAMPLE_AGGREGATED,
                votes=vote_breakdown,
                confidence=aggregated_vote.final_confidence
            )

        # Track end time
        end_time = datetime.now()

        # Build complete aggregate root via factory
        aggregate_run = AggregateRunFactory.create(
            aggregation_strategy_name=self.strategy.get_strategy().name,
            io_config_name=self.output_port.io_name,
            input_run_names=resolved_run_names,
            run_name=self.run_name,
            run_type=RunType.OFFICIAL if official else RunType.TEST,
            aggregated_votes=aggregated_votes,
            start_time=start_time,
            end_time=end_time,
            notes=notes,
        )

        # Write output (batch persistence like ingest)
        write_result = self.output_port.write(aggregate_run)

        # Calculate statistics using domain functions
        total_llm_judgements = calculate_total_judgements(judged_datasets)
        warnings_summary = build_warnings_summary(tie_count, no_valid_votes_count)

        # Construct summary
        summary = AggregateRunSummary(
            start_time=start_time,
            end_time=end_time,
            input_judgement_count=total_llm_judgements,
            unique_pair_count=len(grouped_by_sample),
            output_aggregated_count=len(aggregated_votes),
            tie_count=tie_count,
            no_valid_votes_count=no_valid_votes_count,
            warnings_summary=warnings_summary,
            write_summary=write_result,
        )

        # Write summary.json
        summary_path = write_summary(summary, self.run_dir)
        logger.info(
                AggregateLogEvent.AGGREGATE_SUMMARY_WRITTEN,
                summary_path=summary_path
            )

        return summary
