model_id: gpt-oss-20b
provider: openrouter
context_window: 8192

# Core inference parameters (explicit for discoverability)
temperature: 0.0
max_tokens: 256
seed: 42  # For reproducibility

# Output control
response_format:
  type: json_object  # Force structured JSON output

# Advanced parameters (if needed)
additional_params: {}

# Model capabilities
capabilities:
  multilingual: true

# OpenRouter configuration
openrouter_model_id: openai/gpt-oss-20b:free
