model_id: qwen-0.5b
provider: openrouter
context_window: 8192

# Core inference parameters
temperature: 0.0
max_tokens: 256

# Advanced parameters
additional_params: {}

# Model capabilities
capabilities:
  multilingual: true

# OpenRouter configuration
openrouter_model_id: qwen/qwen-0.5b-chat
