"""Dependency configuration for inference pipeline.

Startup Layer - Composition Root

Hexagonal Architecture - Composition Root Pattern:
Builds and wires together the application hexagon by:
1. Loading configuration from YAML files
2. Creating run directory (infrastructure concern)
3. Instantiating driven adapters (ports implementations)
4. Assembling the use case with its dependencies
5. Returning the application's driving port interface

This is the composition root where all dependency wiring happens.
NOT unit tested - tested via CLI integration tests.

The driving adapter (CLI) calls this configurator to build the application,
then uses the returned ForRunningInference interface to execute business logic.
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional

# Load runtime env configuration (DATABASE_URL, API keys, etc.)
from llm_ensemble.libs.runtime.env import load_runtime_config
load_runtime_config()

from llm_ensemble.infer.application.inference_application import InferenceApplication
from llm_ensemble.infer.application.ports.driving.for_running_inference import ForRunningInference
from llm_ensemble.infer.domain.entities.model_config import ModelConfig
from llm_ensemble.infer.domain.entities.retry_config_schema import RetryConfig

from llm_ensemble.infer.adapters.driven.io_factory import IOAdapterFactory
from llm_ensemble.infer.adapters.driven.provider_factory import ProviderFactory
from llm_ensemble.infer.adapters.driven.prompt_factory import PromptAdapterFactory
from llm_ensemble.infer.adapters.driven.parser_factory import ParserAdapterFactory

from llm_ensemble.infer.startup.config_loader import load_model_config, load_retry_config
from llm_ensemble.libs.runtime.path_manager import PathManager
from llm_ensemble.libs.runtime.tag_manager import TagManager
from llm_ensemble.libs.runtime.run_info import RunType
from llm_ensemble.libs.logging import configure_logger


def build_application(
    provider_name: str,
    io_name: str,
    prompt_template_name: str,
    model_config_name: str,
    retry_config_name: str,
    run_name: str,
    official: bool = False,
    tag: Optional[str] = None,
) -> ForRunningInference:
    """Build and wire the inference application hexagon.

    Pure dependency wiring - no business logic.

    Composition root responsibilities:
    1. Load configuration from YAML files
    2. Create run directory from provided run_name
    3. Instantiate adapter implementations
    4. Wire adapters into application

    The CLI generates the run_name from configuration metadata.

    Args:
        provider_name: Provider name (e.g., 'openrouter', 'ollama')
        io_name: I/O adapter name (e.g., 'json', 'parquet')
        prompt_template_name: Prompt template name (e.g., 'thomas-et-al')
        model_config_name: Model config name (e.g., 'gpt-oss-20b')
        retry_config_name: Retry config name (e.g., 'standard')
        run_name: Run identifier (generated by CLI from config metadata)
        official: Mark as official run (creates in official/ subdirectory)
        tag: Optional tag name for easy reference by downstream CLIs

    Returns:
        Application implementing ForRunningInference interface
    """
    # Load configuration from YAML files
    model_cfg = load_model_config(model_config_name)
    retry_cfg = load_retry_config(retry_config_name)

    # Create run directory
    run_dir : Path = PathManager.get_run_dir("infer", run_name, official)
    run_dir.mkdir(parents=True, exist_ok=True)

    # Configure logging infrastructure
    run_type = RunType.OFFICIAL if official else RunType.TEST
    configure_logger(
        cli_name="infer",
        run_name=run_name,
        run_type=run_type.value,
        log_file_path=run_dir / "run.log",
    )

    # Create tag symlink if requested
    if tag:
        TagManager.create_tag(run_dir, tag)

    # Build application hexagon with loaded configs
    return _build_application_hexagon(
        provider_name=provider_name,
        io_name=io_name,
        prompt_template_name=prompt_template_name,
        model_cfg=model_cfg,
        retry_cfg=retry_cfg,
        run_dir=run_dir,
        run_name=run_name,
    )


def _build_application_hexagon(
    provider_name: str,
    io_name: str,
    prompt_template_name: str,
    model_cfg: ModelConfig,
    retry_cfg: RetryConfig,
    run_dir: Path,
    run_name: str,
) -> InferenceApplication:
    """Build application hexagon by instantiating driven adapters and use case.

    This is the core of hexagonal architecture: assembling the application
    by plugging concrete adapters (driven side) into the use case.

    Driven ports (infrastructure dependencies):
    - InputPort: Reading normalized datasets
    - OutputPort: Writing LLM judgements
    - PromptBuilderPort: Building prompts from samples
    - LLMProviderPort: Calling LLM APIs
    - ResponseParserPort: Parsing LLM responses

    The use case depends only on port abstractions (ABCs), enabling:
    - Unit testing with mocked ports
    - Swapping implementations via configuration

    Logging configuration is read from environment variables during application execution.

    Args:
        provider_name: Provider name for factory
        io_name: I/O adapter name for factory
        prompt_template_name: Prompt template name for factory
        model_cfg: Loaded model configuration
        retry_cfg: Loaded retry configuration
        run_dir: Run directory path (created by composition root)
        run_name: Run identifier (generated by CLI)

    Returns:
        InferenceApplication - the application's driving port interface
    """
    input_port = IOAdapterFactory.create_reader(io_name)
    output_port = IOAdapterFactory.create_writer(io_name, run_dir=run_dir)
    prompt_builder = PromptAdapterFactory.create(prompt_template_name)
    response_parser = ParserAdapterFactory.create(prompt_template_name)
    llm_provider = ProviderFactory.create(provider_name, model_cfg, retry_cfg)

    # Assemble application hexagon (use case with driven ports)
    return InferenceApplication(
        input_port=input_port,
        output_port=output_port,
        prompt_builder=prompt_builder,
        llm_provider=llm_provider,
        response_parser=response_parser,
        run_dir=run_dir,
        run_name=run_name,
    )
